name: direct_select
description: This package allows you to scroll/select the value directly from the dropdown with less effort and time.
version: 1.1.0
homepage: https://twitter.com/diegoveloper
repository: https://github.com/diegoveloper/flutter_direct_select/

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  back_button_interceptor: ^4.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
