name: firebase_realtime_chat
description: Realtime chat for Firebase realtime database
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  sembast: ^3.0.0+4
  sembast_sqflite: ^2.0.0+1
  sqflite: ^2.0.0+3
  firebase_database: ^6.1.0
  mobx: ^2.0.0-nullsafety.5
  mobx_codegen: ^2.0.0-nullsafety.2
  quiver: ^3.0.0
  path_provider: ^2.0.1
  fast_immutable_collections: ^2.0.2

  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage
  log:
    path: /home/projects/packages/flutter_helpers/log
  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  await_route:
    path: /home/projects/packages/flutter_helpers/await_route

dependency_overrides:
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

dev_dependencies:
  build_runner:
