name: firebase_realtime_chat
description: Realtime chat for Firebase realtime database
version: 1.1.0
homepage: github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.5.0
  sembast: ^3.0.2
  sembast_sqflite: ^2.0.0+1
  sqflite: ^2.0.0+3
  firebase_database: ^7.1.2
  mobx: ^2.0.1
  mobx_codegen: ^2.0.1+3
  quiver: ^3.0.0
  path_provider: ^2.0.1
  fast_immutable_collections: ^5.1.2
  flutter_riverpod: ^1.0.3
  freezed_annotation: ^2.0.3
  collection: ^1.16.0

  refresh_storage:
    path: /Users/muru/Projects/packages/flutter_helpers/refresh_storage
  log:
    path: /Users/muru/Projects/packages/flutter_helpers/log
  loader_coordinator:
    path: /Users/muru/Projects/packages/flutter_helpers/loader_coordinator
  await_route:
    path: /Users/muru/Projects/packages/flutter_helpers/await_route

dev_dependencies:
  build_runner:
  flutter_lints:
  freezed: ^2.0.3+1

dependency_overrides:
  mobx:
    path: /Users/muru/Projects/forks/mobx.dart/mobx
  flutter_mobx:
    path: /Users/muru/Projects/forks/mobx.dart/flutter_mobx
  mobx_codegen:
    path: /Users/muru/Projects/forks/mobx.dart/mobx_codegen
