name: firebase_realtime_chat
description: Realtime chat for Firebase realtime database
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya/flutter_helpers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  async: ^2.4.2
  sembast: ^2.4.7+7
  sembast_sqflite: ^1.0.0+1
  sqflite: ^1.3.2+2
  firebase_database: ^4.1.1
  mobx: ^1.2.1+3
  mobx_codegen:
  quiver: ^2.1.3
  path_provider: ^1.6.18
  fast_immutable_collections: ^1.0.28

  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage
  log:
    path: /home/projects/packages/flutter_helpers/log
  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  await_route:
    path: /home/projects/packages/flutter_helpers/await_route

dependency_overrides:
  # Conditionally checks if an observable should update.
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:

flutter:
