name: modal_bottom_sheet
description:
version: 1.0.0
homepage: 'https://github.com/volskaya/flutter_helpers'

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  boxy: ^1.2.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  pedantic: ^1.8.0+1

flutter:
