name: fading_tile
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  flutter_hooks: ^0.16.0

  utils:
    path: /home/projects/packages/flutter_helpers/utils
  log:
    path: /home/projects/packages/flutter_helpers/log
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
