name: admob
description: Admob SDK for Flutter.
version: 0.0.1
author: Roland Volskaya
repository: https://github.com/volskaya/flutter_helpers

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.22.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^0.12.6
  json_annotation:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.11.0
  freezed_annotation: ^0.12.0
  json_serializable:

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed

flutter:
  plugin:
    platforms:
      android:
        package: dev.volskaya.admob
        pluginClass: AdmobPlugin
      ios:
        pluginClass: AdmobPlugin
