name: refresh_storage
description: Wrapper around PageStorage with dispose & refresh mechanism.
version: 0.0.1
homepage: github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^5.0.0
  riverpod: ^1.0.3
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3
  fast_immutable_collections: ^5.1.2

  fancy_switcher:
    path: /Users/muru/Projects/packages/fancy_switcher
  hooks_riverpod: ^1.0.0-dev.7
  flutter_hooks: ^0.18.0

dev_dependencies:
  build_runner:
  freezed: ^2.0.3+1
