name: delayed_progress_indicator
description: A new Flutter package project.
version: 1.0.0
homepage: github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  animations:
    path: /home/projects/packages/flutter_helpers/animations

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
