name: liquid_progress_indicator
description: A progress indicator with water-like effect in Flutter. Works similarly to Flutters own ProgressIndicator.
version: 0.0.1
author: Roland Volskaya
homepage: https://github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
