include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - lib/**.g.dart
    - lib/**.freezed.dart
    - lib/l10n/**

  strong-mode:
    implicit-casts: false
    implicit-dynamic: true

  errors:
    missing_required_param: warning
    missing_return: warning
    todo: ignore
    deprecated_member_use_from_same_package: ignore
    sdk_version_async_exported_from_core: ignore
    invalid_annotation_target: ignore
    directives_ordering: ignore
