name: animations
description: Fancy pre-built animations that can easily be integrated into any Flutter application.
version: 1.1.3
homepage: https://github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.3
  provider: ^5.0.0
  flutter_riverpod: ^1.0.3
  nil: ^1.1.1

  sliver_transform:
    path: /Users/muru/Projects/packages/flutter_helpers/sliver_transform
  utils:
    path: /Users/muru/Projects/packages/flutter_helpers/utils

dev_dependencies:
  flutter_lints:
  build_runner:
  vector_math: ^2.1.0
  freezed: ^2.0.3+1
