name: animations
description: Fancy pre-built animations that can easily be integrated into any Flutter application.
version: 1.1.3
homepage: https://github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sliver_transform:
    path: /home/projects/packages/flutter_helpers/sliver_transform

dev_dependencies:
  vector_math: ^2.1.0
