name: animations
description: Fancy pre-built animations that can easily be integrated into any Flutter application.
version: 1.1.2
homepage: https://github.com/flutter/packages/tree/master/packages/animations

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  vector_math: ^2.0.8
