name: encapsulated_scaffold
description: Scaffold awareness for easier deep-linking and reactions.
version: 0.0.2
author: Roland Volskaya
homepage: github.com/volskaya/encapsulated_scaffold

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  mobx: ^1.2.1+1
  flutter_mobx: ^1.1.0+1
  mobx_codegen: ^1.1.0+1
  provider: ^4.3.1
  back_button_interceptor: ^4.3.1
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.0
  freezed:
    path: /home/projects/forks/freezed/packages/freezed

flutter:
