name: scrollable_positioned_list
version: 0.1.9
description: A list with helper methods to programmatically scroll to an item.
homepage: https://github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ^1.12.13+hotfix.5

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
