name: encapsule
description: Scaffold awareness for easier deep-linking and reactions.
version: 0.1.2
homepage: github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  mobx: 2.0.1
  flutter_mobx: 2.0.0
  mobx_codegen: 2.0.1+3
  provider: ^5.0.0
  back_button_interceptor: ^5.0.0
  json_annotation: ^4.0.1
  freezed_annotation: ^0.14.1

  fancy_switcher:
    path: /home/projects/packages/fancy_switcher

dev_dependencies:
  build_runner:
  json_serializable: ^5.0.0
  freezed: ^0.14.1+1

dependency_overrides:
  mobx_codegen:
    path: /home/projects/forks/mobx.dart/mobx_codegen
