name: utils
version: 0.1.1
homepage: github.com/volskaya/flutter_helpers
publish_to: "none"

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  mobx: ^2.0.7+2
  firebase_storage: ^10.0.1
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  cloud_functions: ^3.0.0
  cloud_firestore: ^3.1.6
  quiver: ^3.0.0
  json_annotation: ^4.5.0
  flutter_hooks: ^0.18.0
  flutter_riverpod: ^1.0.3
  provider: ^5.0.0

  loader_coordinator:
    path: /Users/muru/Projects/packages/flutter_helpers/loader_coordinator
  log:
    path: /Users/muru/Projects/packages/flutter_helpers/log
  refresh_storage:
    path: /Users/muru/Projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  build_runner:
  json_serializable: ^6.2.0
  freezed: ^2.0.3+1

dependency_overrides:
  mobx:
    path: /Users/muru/Projects/forks/mobx.dart/mobx

flutter:
  generate: true
