name: utils
version: 0.1.1
author: Roland Volskaya
homepage: github.com/volskaya/flutter_helpers

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  mobx: ^2.0.1
  firebase_storage: ^8.1.0
  freezed_annotation: ^0.14.1
  intl: ^0.17.0
  cloud_functions: ^1.1.0
  cloud_firestore: ^2.2.0
  quiver: ^3.0.0
  json_annotation: ^4.0.1

  loader_coordinator:
    path: /home/projects/packages/flutter_helpers/loader_coordinator
  log:
    path: /home/projects/packages/flutter_helpers/log
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  json_serializable: ^4.1.0
  build_runner: ^1.10.0
  freezed: ^0.14.1+1

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed

flutter:
  generate: true
