name: loader_coordinator
description: Loader coordinator store
version: 0.0.1
author: Roland Volskaya
homepage: github.com/volskaya/flutter_helpers
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
