name: revealing_bar
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^0.12.6
  provider: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed_annotation: ^0.12.0
  build_runner: ^1.10.0

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed

flutter:
