name: revealing_bar
version: 1.1.0
homepage: github.com/volskaya
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.3
  provider: ^5.0.0
  flutter_riverpod: ^1.0.3

dev_dependencies:
  freezed: ^2.0.3+1
  build_runner:
