name: revealing_bar
version: 1.1.0
author: Roland Volskaya
homepage: github.com/volskaya
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^0.14.1
  provider: ^5.0.0

dev_dependencies:
  freezed: ^0.14.1+1
  build_runner: ^1.10.0

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed
