name: carousel_slider
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  utils:
    path: /home/projects/packages/flutter_helpers/utils
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  firebase_image:
    path: /home/projects/packages/firebase_image
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
