name: carousel_slider
version: 1.1.0
homepage: github.com/volskaya
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^0.14.1
  flutter_riverpod: 1.0.0-dev.7

  utils:
    path: /home/projects/packages/flutter_helpers/utils
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  firebase_image:
    path: /home/projects/packages/firebase_image
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  build_runner:
  freezed: ^0.14.1+1
