name: carousel_slider
version: 1.1.0
homepage: github.com/volskaya
publish_to: none

environment:
  sdk: ">=2.18.0-44.0.dev <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

  freezed_annotation: ^2.0.3
  flutter_riverpod: ^1.0.3

  utils:
    path: /Users/muru/Projects/packages/flutter_helpers/utils
  fancy_switcher:
    path: /Users/muru/Projects/packages/fancy_switcher
  firebase_image:
    path: /Users/muru/Projects/packages/firebase_image
  refresh_storage:
    path: /Users/muru/Projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  build_runner:
  freezed: ^2.0.3+1
