name: carousel_slider
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  freezed: ^0.12.6

  utils:
    path: /home/projects/packages/flutter_helpers/utils
  fancy_switcher:
    path: /home/projects/packages/fancy_switcher
  firebase_image:
    path: /home/projects/packages/firebase_image
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  build_runner: ^1.10.0
  freezed_annotation: ^0.12.0

dependency_overrides:
  freezed_annotation:
    path: /home/projects/forks/freezed/packages/freezed_annotation
  freezed:
    path: /home/projects/forks/freezed/packages/freezed

flutter:
