name: material_dialog
version: 2.0.0
author: Roland Volskaya
homepage: github.com/volskaya
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  boxy: ^1.2.0+1
  animations:
    path: /home/projects/packages/flutter_helpers/animations
  refresh_storage:
    path: /home/projects/packages/flutter_helpers/refresh_storage

dev_dependencies:
  flutter_test:
    sdk: flutter
