name: future_card_button
description: Asynchronous button with an animated indicator.
version: 1.0.0
author: Roland Volskaya
homepage: github.com/volskaya/future_card_button
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  fancy_switcher:
    path: /Users/muru/Projects/packages/fancy_switcher
  loader_coordinator:
    path: /Users/muru/Projects/packages/flutter_helpers/loader_coordinator
